apiVersion: v1
kind: Service
service:
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
metadata:
  name: frontend-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
